name: "screenshots-ci-action"
description: "Screenshot a website with different viewpoints"
author: "JackyHu <flameddd@hotmail.com>"
branding:
  icon: 'monitor'
  color: 'blue'
inputs:
  url:
    required: true
    description: "The website URL you want to screenshot. e.x.: https://www.google.com/"
  noDesktop:
    required: false
    description: "Not screenshot website's desktop viewpoint"
    default: false
  devices:
    required: false
    description: "Screenshot specific mobile devices viewpoint. e.x.: 'iPhone 6' 'Galaxy S III landscape' 'iPad Pro landscape'"
  fullPage:
    required: false
    description: "When true, takes a screenshot of the full scrollable page. Defaults to false"
    default: false
  type:
    required: false
    description: "Specify screenshot type, can be either jpeg or png. Defaults to 'jpeg'."
    default: 'jpeg'
  noCommitHashFileName:
    required: false
    description: "Screenshot filename don't include commit hash."
    default: false
  waitUntil:
    required: false
    description: "When to consider navigation succeeded, defaults to 'networkidle0'."
    default: 'networkidle0'
  waitForSelector:
    required: false
    description: "Wait for the selector to appear in page. If at the moment of calling the method the selector already exists, the method will return immediately. If the selector doesn't appear after the timeout milliseconds of waiting, the function will throw."
    default: ''
  waitForSelectorHidden:
    required: false
    description: 'Wait for the selected element to not be found in the DOM or to be hidden, i.e. have display: none or visibility: hidden CSS properties.'
    default: 'false'
  waitForSelectorVisible:
    required: false
    description: 'Wait for the selected element to be present in DOM and to be visible, i.e. to not have display: none or visibility: hidden CSS properties.'
    default: 'false'
  waitForSelectorTimeout:
    required: false
    description: 'Maximum time to wait in milliseconds. Pass 0 to disable timeout.'
    default: 30000 
runs:
  using: 'node16'
  main: "dist/index.js"