name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install puppeteer
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn
    - run: npm ci
    - uses: ./
      with:
        url: https://github.com
        devices: iPhone 6,iPhone 6 landscape,Nexus 7,Pad Pro,Galaxy S III landscape,iPad Pro landscape
    - uses: actions/upload-artifact@v1
      with:
        name: Download-screenshots
        path: screenshots