name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        url: https://github.com
        devices: |
          "iPhone 6"
          "iPhone 6 landscape"
          "Nexus 7"
          "Pad Pro"
          "Galaxy S III landscape"
          "iPad Pro landscape"
    - run: npm ci
    - run: npm test
  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        url: https://github.com
        devices: |
          "iPhone 6"
          "iPhone 6 landscape"
          "Nexus 7"
          "Pad Pro"
          "Galaxy S III landscape"
          "iPad Pro landscape"